# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: testing-workflow CI 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 

jobs:
  build:
    name: Package & test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
    - uses: actions/checkout@v2

    - name: Use Node.js 16.14.2
    - uses : actions/setup-node@v2
      with:
        node-version: "16.14.2"
        cache: "npm"

    - name: Install dependencies
      run: npm install

    - name : Test
      run: npm test

    - name: Build
      run: npm build
      
  buildImageAndPush:
    name: Publish to docker.io
    runs-on: ubuntu-latest

    steps:
      - name: Build and push docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: cuissto59/testing-workflow
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

